# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blockchain.proto',
  package='schema',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x62lockchain.proto\x12\x06schema\"/\n\x05\x42lock\x12\x15\n\rprevious_hash\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"@\n\x15\x42lockchainDescription\x12\x14\n\x0cgenesis_hash\x18\x01 \x01(\t\x12\x11\n\thead_hash\x18\x02 \x01(\tb\x06proto3')
)




_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='schema.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='previous_hash', full_name='schema.Block.previous_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='schema.Block.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=75,
)


_BLOCKCHAINDESCRIPTION = _descriptor.Descriptor(
  name='BlockchainDescription',
  full_name='schema.BlockchainDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='genesis_hash', full_name='schema.BlockchainDescription.genesis_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head_hash', full_name='schema.BlockchainDescription.head_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['BlockchainDescription'] = _BLOCKCHAINDESCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:schema.Block)
  ))
_sym_db.RegisterMessage(Block)

BlockchainDescription = _reflection.GeneratedProtocolMessageType('BlockchainDescription', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKCHAINDESCRIPTION,
  __module__ = 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:schema.BlockchainDescription)
  ))
_sym_db.RegisterMessage(BlockchainDescription)


# @@protoc_insertion_point(module_scope)
